In [1]:
print("hello")
print('hellooo')

hello
hellooo


In [ ]:
# lambda function


# a=range(1,10)
# b=lambda x:'yes' if x in a else 'no'


In [ ]:
# a=lambda x,y:x+y
# print(a(3,5))




# a=lambda x,y:x+y
# print(a(34,4))
# a=lambda x,y:x+y
# print(a(45,34))

# a=lambda x,y:x*y
# print(a(3,45))

79


In [ ]:
# filter in lambda function



# a=[1,2,3,4,5,6,7,8,9,10]

# def filter(a):
    
#     b=[]
    
#     for i in a:
#         if i%2==0:
#             b.append(i)
#     return b
# filter(a)        
   
     
     
# a=[1,2,3,4,5,6,7,8,9]

# def filter(a):
#     b=[]
    
    
    
#     for i in a:
#         if i%2==1:
#             b.append(i)
#     return b
# print(filter(a))

            
            
            
            

[1, 3, 5, 7, 9]


In [ ]:
# map function


# a=[1,2,3,4,5,6,7,8,9,10]
# b=list(map(lambda x:x+1,a))
# print(b)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
# a=[2,3,4,5,6,7,8,9,10]
# b=list(map(lambda x:x*2,a))
# print(b)


# a=[2,3,4,5,6,7,8,9,10]
# b=list(map(lambda x:x-2,a))
# print(b)




[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# from functools import reduce

# a=[1,2,3,4]
# b=reduce(lambda x,y:x+y,a)
# print(b)





# from functools import reduce

# a=[2,3,4,5,6,7,9]
# b=reduce(lambda x,y:x+y,a)
# print(b)

36


In [1]:
def cal_per(a,b,c):
    avg=(a+b+c)/3
    return avg



cal_per(23,45,67)

45.0

In [4]:
# def cal_per(*args):
#     avg=sum(args)/len(args)
    
#     return avg
# cal_per(2,3,4,5,7)

def cal_per(*args):
    avg=sum(args)/len(args)
    
    return avg

cal_per(23,45,67,89)



56.0

In [5]:
def cal_average(*args):
    avg=sum(args)/len(args)
    
    return avg

print(cal_average(2,3,4,5,67,9))

15.0


In [8]:
def cal_per(**args):
    print(type(args))
    print(args)
    avg=sum(args.value())/len(args)
    return avg


cal_per(mohit=23,tarun=234,sameer=455,ravi=789)
    
    

<class 'dict'>
{'mohit': 23, 'tarun': 234, 'sameer': 455, 'ravi': 789}


AttributeError: 'dict' object has no attribute 'value'

In [14]:
def cal_per(**args):
    print(type(args))
    print(args)

   
    avg=sum(args.values())/len(args)
    return avg


cal_per(mohit=23,tarun=234,sameer=455,ravi=789)

<class 'dict'>
{'mohit': 23, 'tarun': 234, 'sameer': 455, 'ravi': 789}


375.25

In [15]:
def average_part(**args):
    print(type(args))
    print(args)
    
    avg=sum(args.values())/len(args)
    return avg



average_part(mohit=23,yellow=242,erer=232)

<class 'dict'>
{'mohit': 23, 'yellow': 242, 'erer': 232}


165.66666666666666

In [16]:
def average_sum(**args):
    print(type(average_sum))
    print(average_sum)
    
    
    avg=sum(args.values())/len(args)
    
    return avg


average_sum(mohit=23,tarun=21)

<class 'function'>
<function average_sum at 0x000001B43A10F1C0>


22.0

In [ ]:
# def main(func):
#     def operation():
#         print("This is wrapper function class")
#         func()
#         print("We are learning decorator")
#     return operation   # ← ye main se return hoga

# # Example function
# def display():
#     print("This is original function")

# # Applying decorator manually
# my_decorator = main(display)
# my_decorator()


This is wrapper function class
This is original function
We are learning decorator


In [21]:
def main(func):
    def operation():
        print("hello sir who are you")
        func()
        print("the are the number of element of ducate")
        
    return operation
def sum():
    print("hello sir kaise ho")
    
    
my_decorator=main(sum)

my_decorator()    
        
    

hello sir who are you
hello sir kaise ho
the are the number of element of ducate


In [ ]:
# def main(func):
#     def operation():
#       print("hello sir who are you")
#       func()
#       print("they are not eligible")
#     return operation


# def sum():
#     print("they are not fount")



# main(sum)()    
      
      
      
    
    

hello sir who are you
they are not fount
they are not eligible


In [ ]:
# r=lambda a:a+15

# print(r(10))

# r=lambda x,y:x*y



# print(r(12,23))

# lambda_15=lambda x:x+15

# lambda_multiply=lambda x,y:x*y



# print("add 15 and 12",lambda_15(12))


# print( "multiply 12 and 14",lambda_multiply(12,14))



















add 15 and 12 27
multiply 12 and 14 168


In [ ]:
# lambda function question in python
# 1 lambda function add and multiply
# a=lambda x:x+15
# b=lambda x,y:x*y

# print(a(13))
# print(b(23,45))


28
1035


In [29]:
def multiply_with(n):
    return lambda x: x * n

# yahan n = 2 (unknown number)
result = multiply_with(2)

print(result(15))  # output: 30


30


In [ ]:
# Function lambda generate

def  multiply(n):
    return lambda x:x*n

result=multiply(2)
print(result(15))

result=multiply(3)
print(result(16))


result=multiply(5)
print(result(17))
    

30
48
85


In [ ]:
# integer filter Lambda list
# even list

a=[1,2,3,4,5,6,7,8,9,10]

b=list(filter(lambda a:a%2==0,a))
print(b)

[2, 4, 6, 8, 10]


In [35]:
# odd list 

a=[1,2,3,4,5,6,7,8,9,10]
b=list(filter(lambda a:a%2==1,a))
print(b)

[1, 3, 5, 7, 9]


In [ ]:
# square  and cube lambda function

# a=[1,2,3,4,5,6,7,8,9,10]
# b=list(map(lambda a:a**2,a))
# print(b)



# cube in number

# a=[1,2,3,4,5,6,7,8,9,10]

# b=list(map(lambda a:a**3,a))
# print(b)


[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [ ]:
# string start check lambda
start_variable = lambda x: True if x.startswith('p') else False

print(start_variable('python'))  
print(start_variable('java'))    





True
False


In [51]:
# date time lambda



import datetime

now=datetime.datetime.now()

print(now)



year=lambda x:x.year
print(year(now))

month=lambda x:x.month
print(month(now))

day=lambda x:x.day
print(day(now))


time=lambda x:x.time()
print(time(now))






2025-11-06 12:51:07.441663
2025
11
6
12:51:07.441663


In [ ]:
 




# is_number=lambda s:s.replace('.','',1).isdigit()


# print(is_number('123'))
# print(is_number('22.92'))
# print(is_number('abc'))
# print(is_number('12a23'))






True
True
False
False


In [ ]:
# array_number1=[1,2,3,4,5,6,7,8,9]
# array_number2=[1,2,3,4,5,6,7,8]

# print(array_number1)
# print(array_number2)

# result=list(filter(lambda x:x in array_number1,array_number2))

# print("insert two array",result)
# Write a Python program to find the intersection of two given arrays using Lambda.

array_one=[1,2,3,4,6,7,8,9,10]
array_two=[1,2,3,4,5,6,7]
print(array_one)
print(array_two)



result=list(filter(lambda x:x in array_one,array_two))
print('/insert of array in',result)




[1, 2, 3, 4, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7]
/insert of array in [1, 2, 3, 4, 6, 7]


In [ ]:
# arr=[-12,-13,-4,-6,12,34,5,6,8,10]


# position=list(filter(lambda x:x>0,arr))
# negative=list(filter(lambda x:x<0,arr))


# result=negative+position

# print(result)


[-12, -13, -4, -6, 12, 34, 5, 6, 8, 10]


In [14]:
array=[1,2,3,4,5,-23,-12,-45,-12]


postion=list(filter(lambda x: x>0,array))
negative=list(filter(lambda x:x<0,array))


result=negative+postion
print(result)


print(array)


[-23, -12, -45, -12, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, -23, -12, -45, -12]


In [15]:
# Write a Python program to count the even and odd numbers in a given array of integers using Lambda.
array=[1,2,3,4,5,6,7,8,9,10]
print(array)

array1=list(filter(lambda x:x%2==0,array))


array2=list(filter(lambda x:x%2==1,array))

print("sum array value ",array1)

print("odd array value",array2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sum array value  [2, 4, 6, 8, 10]
odd array value [1, 3, 5, 7, 9]


In [ ]:
# numbers = [36, 45, 38, 52, 57, 78, 98, 130]
# print(numbers)

# even_list = list(filter(lambda x: (x % 19 == 0 or x % 13 == 0), numbers))

# print(even_list)




[36, 45, 38, 52, 57, 78, 98, 130]


TypeError: 'list' object is not callable

In [5]:
# Write a Python program that sums the length of a list of names after removing those that start with lowercase letters. Use the lambda function.


name=['Ravi','Ankit','Suman','deepak','manish']


fitered_name=list(filter(lambda x:x[0].isupper(),name))

total_length=sum(map(lambda x:len(x),fitered_name))

print("name sfter removing lowercase onces:",fitered_name)
print("sum of their length ",total_length)

name sfter removing lowercase onces: ['Ravi', 'Ankit', 'Suman']
sum of their length  14


In [ ]:
# name= ['sally', 'Dylan', 'rebecca', 'Diana', 'Joanne', 'keith']

# filter_list=list(filter(lambda x:x[0].isupper(),name))


# result=sum(map(lambda x:len(x),filter_list ))



# print('name after removing lowercase',filter_list)

# print("total element of capital letter",result)



name after removing lowercase ['Dylan', 'Diana', 'Joanne']
total element of capital letter 16


In [ ]:
# OOps start  in python

In [ ]:
# Class and Object  

In [1]:
class my_class:
    a="uvesh"
myclass=my_class()
my_class().a

'uvesh'

In [ ]:
class My_class:
    a='shivam'
    b='tarun'
    c='tttt'
    
    def conc(self):
        return self.a+" "+self.b
    
    def mult(self,count):
        return self.c*count
    
myclass=My_class()
    
print(myclass.a)
print(myclass.b)
print(myclass.conc())

myclass.mult(5)

shivam
tarun
shivam tarun


'tttttttttttttttttttt'

In [10]:
class My_class:
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
        
    def conc(self):
        return self.a+" "+self.b
    
    def mult(self,count):
        return self.c*count
    
    
myclass=My_class('tarun','anu',40)
    
print(myclass.a)
myclass.b
myclass.conc()
    
    
myclass.mult(5)
    
    

tarun


200

In [ ]:
 
class My_class:
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
        
    def add(self):
        return self.a+" "+self.b
    
    def mult(self):
        return self.a* self.b
    def sub(self):
        return self.a-self.b
    def divisable(self):
        return self.a/self.b
    
    
    
myclass=My_class(34,46)
print(m)
    
            
     
        
    
    
    
    

In [ ]:
#################################################################################

In [6]:
import numpy as np

arr2=np.array([[2,3,4,5,6],[1,2,3,4,5]])
print(arr2)
print(type(arr2))
print(arr2.ndim)

[[2 3 4 5 6]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>
2


In [9]:
arr3=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,22,33,44,55]]])
print(arr3)
print(arr3.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 22 33 44 55]]]
3


In [13]:
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [15]:
ar5=np.array([[[[[1,2,3,4],[11,12,14,14],[21,22,23,24]]]]])
print(ar5)
print(ar5.ndim)

[[[[[ 1  2  3  4]
    [11 12 14 14]
    [21 22 23 24]]]]]
5


In [17]:
import numpy as np
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
import numpy as np

a1=np.zeros(5)
a2=np.zeros((4,5))
print(a1)
print()
print(a2)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# arr_one=np.ones(5)
# print(arr_one)
# print()
# arr_=np.ones((4,6))
# print(arr_)





arr=np.arange(5)
print(arr)

[0 1 2 3 4]


In [25]:
a11=np.zeros(5)
print(a11)

print()
a12=np.ones((4,4))
print(a12)

[0. 0. 0. 0. 0.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
arr=np.eye(5)
print(arr)

print()
arr2=np.eye(7)
print(arr2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [32]:
ar_ =np.eye(4,5)
print(ar_)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [38]:
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)
arr_lin1=np.linspace(0,10,num=5)
print(arr_lin1)

arr_lin2=np.linspace(0,20,num=4)
print(arr_lin2)


arr_line3=np.linspace(0,10,num=4)
print(arr_line3)

[ 1.    3.25  5.5   7.75 10.  ]
[ 0.   2.5  5.   7.5 10. ]
[ 0.          6.66666667 13.33333333 20.        ]
[ 0.          3.33333333  6.66666667 10.        ]


In [39]:
import numpy as np

var=np.random.rand(4)
print(var)
 


[0.25558384 0.34930405 0.26981019 0.34147275]


In [41]:
var2=np.random.rand()
print(var2)
var1=np.random.rand(2,5)
print(var1)

0.31618417767832296
[[0.99729104 0.09229213 0.59235599 0.3804975  0.86011003]
 [0.64872163 0.40220646 0.67160056 0.3568357  0.76036165]]


In [43]:
var2=np.random.rand(6)
print(var2)
var21=np.random.rand(2,6)
print(var21)

[0.92728712 0.0219406  0.37907608 0.19904169 0.66265967 0.80157517]
[[0.35281    0.33533861 0.18254261 0.01674041 0.01771864 0.53556825]
 [0.61928198 0.98456195 0.48455057 0.48154133 0.81272185 0.65096784]]


In [44]:
var3=np.random.ranf(4)
print(var3)

[0.2407366  0.55444476 0.95383458 0.54545896]


In [46]:
var4=np.random.ranf(4)
print(var4)

[0.91000554 0.07891046 0.8333636  0.04321105]


In [47]:
var33=np.random.randint(5,20,5)
print(var33)

[ 8 15 19 14  5]


In [53]:
import numpy as np
varr=np.array([1,2,3,4,5,6])
print("datatype" ,varr.dtype)
var=np.array([123,233,3,4,5,6,7,8,9,0,12,11,12,12,13,14,24])
print("data type",var.dtype)

datatype int64
data type int64


In [57]:
var=np.array([1.0,1.2,1.3])
print("data  type",var.dtype)

data  type float64


In [60]:
var=np.array(['a','e','i','o','u'])
print(var)
print(var.dtype)

['a' 'e' 'i' 'o' 'u']
<U1


In [62]:
var=np.array(['a','e','i','o','ss'])
print(var)
print(var.dtype)

['a' 'e' 'i' 'o' 'ss']
<U2


In [65]:
var=np.array(['a','s','d','f','1','2','3','4','5'])
print(var)
print(var.dtype)

['a' 's' 'd' 'f' '1' '2' '3' '4' '5']
<U1


In [74]:
x=np.array([1,2,3,4])
print("data type:",x.dtype)
print(x)
print()

x=np.array([1,2,3,4],dtype=np.int8)
print("data type:",x.dtype)
print(x)

data type: int64
[1 2 3 4]

data type: int8
[1 2 3 4]
