In [5]:
import sys
print(sys.executable)



c:\Users\Dell\AppData\Local\Programs\Python\Python310\python.exe


In [6]:
! "C:\Users\Dell\AppData\Local\Programs\Python\Python310\python.exe" -m pip install numpy


  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np
print('hello')
print('gf')

hello
gf


In [8]:
import numpy as np


li=[1,2,3,4,5,6,7]
li=[x+5 for x in li]
print(li)

[6, 7, 8, 9, 10, 11, 12]


In [9]:
a=np.array([1,2,3,4,5,6,7])
print(a.dtype)

int64


In [10]:
import numpy as np

li=[1,2,3,4,5]

arr=np.array(li)

print(arr)


[1 2 3 4 5]


In [11]:
import numpy as np

li=[1,2,3,4,5,6]
arr=np.array(li)
print(arr+4)
print(arr*4)

[ 5  6  7  8  9 10]
[ 4  8 12 16 20 24]


In [ ]:
# import numpy as np


# li=[2,3,4,5,6,7,8]
# arr=np.array(li)
# print(arr)

[2 3 4 5 6 7 8]


In [ ]:
import numpy as np


li=[2,3,4,5,6,7,8]

arr=np.array(li)
print(arr)


[2 3 4 5 6 7 8]


In [4]:
import numpy as np

a=np.array(6)
print(a.shape)
print(a.ndim)

()
0


In [12]:
import numpy as np

a=np.array([[1,2,3,4],[4,5,6,7],[44,55,66,77]])
print(a)

print(a[:,:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [44 55 66 77]]
[[ 1  2]
 [ 4  5]
 [44 55]]


In [16]:
import numpy as np

a=np.array([[1,2,3],[5,6,7],[9,10,11],[12,13,14]])

    
print(a)
print(a.shape)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [12 13 14]]
(4, 3)


In [ ]:
import numpy as np
# a=np.array([[1,2,3],[4,5,6],[44,55,66]],[[44,55,66],[34,12,34],[234,456,34]],[[34,23,45],[434,23,23],[34,45,45]])



In [ ]:

import numpy as np
a=np.array([[1,2,3],[3,4,5],[6,7,8],[34,12,3]])



In [22]:
a=np.array([1,2,3,4,5,6,7])
b=a.view()
b[3]=56
print(a)
print(b)



[ 1  2  3 56  5  6  7]
[ 1  2  3 56  5  6  7]


In [6]:
import numpy as np

listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

print(listarray)
print(listarray.dtype)
print(listarray.shape)
print(listarray.size)


[[1 2 3]
 [5 8 5]
 [0 3 1]]
int64
(3, 3)
9


In [8]:
# list1=[1,2,3]
# list2=[4,5,6]
# arr_list1_2=np.array([list1,list2])
# print(arr_list1_2)

li=np.array([[1,2,3],[4,5,6]])
print(li)

[[1 2 3]
 [4 5 6]]


In [ ]:
# a=np.array([[1,2,3,4],[4,5,6,7],[44,55,66,77]])
# print(a)
# print(a[1,2])


[[ 1  2  3  4]
 [ 4  5  6  7]
 [44 55 66 77]]
6


In [5]:
a=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
     [[10,20,30],[11,12,13],[7,8,9]],
     [[100,200,300],[110,120,130],[7,8,9]]
     ])
print(a)

# print(a[2][1][1])
# print(a[1][0][1])
# print(a[1][0][1])
# print(a[2][0,2])


# print(a[2][1,1])


# print(a[1][1,1])
print(a[1:0,0,1])
# print(a[2][0][1])



print(a)






 



NameError: name 'np' is not defined

In [4]:
a=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
     [[10,20,30],[11,12,13],[7,8,9]],
     [[100,200,300],[110,120,130],[7,8,9]]
     ])

print(a)
print(a[2,:2])
print('hello')
# # print(a[:2,:2,1:])
print(a[:2,:2,1:])






NameError: name 'np' is not defined

In [3]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],
     [[10,20,30],[11,12,13],[7,8,9]],
     [[100,200,300],[110,120,130],[7,8,9]]
     ])

print(a)

NameError: name 'np' is not defined

In [10]:
import numpy as np

a=np.array([[[1,2,3],[4,5,6],[7,8,9]],
     [[10,20,30],[11,12,13],[7,8,9]],
     [[100,200,300],[110,120,130],[7,8,9]]
     ])

print(a)
print(a[1,0:2])

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 11  12  13]
  [  7   8   9]]

 [[100 200 300]
  [110 120 130]
  [  7   8   9]]]
[[10 20 30]
 [11 12 13]]


In [50]:
a=np.array([[[1,2,3],[4,5,6],[17,18,19]],
     [[10,20,30],[11,12,13],[27,28,29]],
     [[100,200,300],[110,120,130],[37,38,39]]
     ])

print(a)
print('hello')
# print(a[1,1:2,0:2])

# print(a[:2,:1])
print()
print(a[:2,1:3])

[[[  1   2   3]
  [  4   5   6]
  [ 17  18  19]]

 [[ 10  20  30]
  [ 11  12  13]
  [ 27  28  29]]

 [[100 200 300]
  [110 120 130]
  [ 37  38  39]]]
hello

[[[ 4  5  6]
  [17 18 19]]

 [[11 12 13]
  [27 28 29]]]


In [ ]:
import numpy as np
a=np.random.rand(50)

print(a)

[0.81117423 0.68365901 0.13694335 0.7184951  0.30913637 0.20928998
 0.97568188 0.0525049  0.8639802  0.61814216 0.64844506 0.19148208
 0.33365327 0.91325759 0.53219651 0.75238256 0.63377093 0.03726524
 0.0926749  0.15824413 0.53953715 0.0391716  0.22430659 0.55131325
 0.4099776  0.8159573  0.05803861 0.29689067 0.14730237 0.91211055
 0.97050928 0.33993013 0.92278969 0.3362578  0.28303607 0.95067327
 0.91082473 0.42602894 0.46856839 0.7518568  0.74627099 0.57781697
 0.88380953 0.6393338  0.10541707 0.2635377  0.7364448  0.5670818
 0.35222651 0.4076823 ]


In [2]:
b=np.arange(1,100,25)
print(b)

[ 1 26 51 76]


In [3]:
np.mean(a)

np.float64(0.5061416342976208)

In [4]:
np.quantile(a,.25)

np.float64(0.26841228898498115)

In [5]:
# percentile in numpy


np.min(a)

np.float64(0.03726523849179009)

In [7]:

np.arange(1,51,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [12]:
np.quantile(a,.25)


np.float64(0.26841228898498115)

In [20]:
a=np.zeros((4,8))
print(a)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
a=np.ones((4,8))
a[1:3,1:7]=0
print(a)



[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a=np.identity(5)
print(a)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 1 26 51 76]


In [ ]:
a=np.eye(3,3,k=1)
print(a)

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.array([1,2,3,0])
b=np.array([7,8,9,0])

np.stack([a,b],axis=0)



array([[1, 2, 3, 0],
       [7, 8, 9, 0]])

In [ ]:
# reshapping

In [ ]:
a=np.arange(25)
a.reshape(1,5,5)




array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [58]:
a=np.arange(30)
a.reshape(2,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [ ]:
a=np.arange(30)
b=a.reshape(2,5,3)
print(b)
c=b.reshape(5,6)
c.reshape(-1)



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
a=np.ones(3,3)
b=np.zeros(3,3)
c=np.stack([a,b],axis=0)
d=np.stack([c,d],axis=1)

print(a)
print(b)
print(c)
print(d)










TypeError: Cannot interpret '3' as a data type

In [ ]:
#1.find commom element from two error in numpy



import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

comman=np.intersect1d(a,b)
print(comman)


[3 4 5]


In [ ]:
#2. find the unique element of error 


# print("\nRow-wise sort (axis=1):")
# print("\nRow-wise sort (axis=1):")
# print("\nColumn-wise sort (axis=0):")
#3. find the index of min val or max val 

#4. concaTE TWO D ERROR 




import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

comman=np.intersect1d(a,b)
print(comman)

In [ ]:
import numpy as np

a = np.array([10, 5, 20, 3, 15])



print(np.argmin(a)) 
print(np.argmax(a)) 

 


3
2


In [ ]:
import numpy as np

a = np.array([[3, 1, 2],
              [9, 5, 4],
              [6, 8, 7]])

print("Original Array:")


print(a)
print("\ncolumn-wise sort")

print(np.sort(a, axis=1))

print("\nRow-wise sort")

print(np.sort(a, axis=0))


Original Array:
[[3 1 2]
 [9 5 4]
 [6 8 7]]

column-wise sort
[[1 2 3]
 [4 5 9]
 [6 7 8]]

Row-wise sort
[[3 1 2]
 [6 5 4]
 [9 8 7]]


In [22]:


a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              
              [10, 11, 12]
              ])


np.concatenate((a, b), axis=0)
# np.concatenate((a,b),axis=1)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
import numpy as np


x=np.array([1,2,3,4,5,6,7])
print(x)
print(type(x))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [7]:
x=[1,2,3,4,5]
ar=np.array(x)
print(ar)

ar=np.array([1,2,3,4,5,6])
print(ar)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [8]:
ar=np.array([1,2,3,4,5,6])
ar

array([1, 2, 3, 4, 5, 6])

In [9]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
l=[]
a=int(input('Enter the no. of elements to be store in array:-'))
for i in range(0,a):
    b=int(input("Enter the element:"))
    l.append(b)

print(np.array(l))
    

[45 23]


In [6]:

import numpy as np
l=[]
a=int(input("enter the no of element to be store in array"))
for i in range(0,a):
    b=int(input("enter the element :"))
    l.append(b)
arr=np.array(l)
    
    
    
print(np.array(arr))

[1 2 3]


In [9]:
arr=np.array([1,2,3,4,5,7])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 7]
<class 'numpy.ndarray'>
1


In [14]:
arr1=np.array([[1,2,3,4],[1,4,5,7]])
print(arr1)
print(arr1.ndim)

[[1 2 3 4]
 [1 4 5 7]]
2


In [18]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5]])
print(arr2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

AttributeError: module 'numpy' has no attribute 'array6'

In [5]:
import numpy as np
ar11=np.array([1,2,3,5,7])
print(ar11)

[1 2 3 5 7]


In [7]:
x=[1,2,3,4,5,6]
print(x)
print(type(x))

[1, 2, 3, 4, 5, 6]
<class 'list'>


ValueError: invalid literal for int() with base 10: '.'

In [13]:
ar=np.array([1,2,3,4,5])
print(ar)
print(type(ar))
print(ar.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [17]:
ar2=np.array([[3,4,5,6,7],[23,34,55,12,12]])

print(ar2)
print(ar2.ndim)
print(type(ar2))

[[ 3  4  5  6  7]
 [23 34 55 12 12]]
2
<class 'numpy.ndarray'>


In [ ]:
ar3=np.array([[[11,12,13,14,15,16],[111,112,113,114,115,118],[56,67,78,23,25,11]]])
print(ar3)
print(ar3.ndim)




[[[ 11  12  13  14  15  16]
  [111 112 113 114 115 118]
  [ 56  67  78  23  25  11]]]
3


In [21]:
arn=np.array([1,2,3,4,6],ndmin=10)
print(arn)

[[[[[[[[[[1 2 3 4 6]]]]]]]]]]


In [24]:
array=np.array([11,12,13,14,15],ndmin=10)
print(array)

[[[[[[[[[[11 12 13 14 15]]]]]]]]]]


In [27]:
import numpy as np

ar_zeros=np.zeros(9)
ar_zeros1=np.zeros((3,4))


print(ar_zeros)
print()
print(ar_zeros1)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
ar_zeros=np.zeros(5)
ar_zeros1=np.zeros((4,5))
print(ar_zeros)
print()
print(ar_zeros1)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
arr1=np.zeros(3)
arr2=np.zeros((3,4))

print(arr1)
print()
print(arr2)

[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:

arr_empty=np.empty(4)
print(arr_empty)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.04657569e-312]


In [38]:
arr_empty=np.empty(8)
print(arr_empty)

[0.000e+000 0.000e+000 0.000e+000 0.000e+000 0.000e+000 9.545e-321
 0.000e+000 0.000e+000]


In [39]:
ar=np.arange(4)
print(ar)

[0 1 2 3]


In [40]:
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [41]:
# identity matrix



ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
array=np.eye(3)
print(array)


arr12=np.eye(5,4)
print()
print(arr12)




[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [46]:
arr_dia=np.eye(3,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [51]:
# linspace



arr_lin=np.linspace(1,10,num=5)

print(arr_lin)



ar=lin=np.linspace(0,10,num=8)
print(ar)


arr3=np.linspace(1,5,num=23)
print(arr3)


arr4=np.linspace(1,5,num=10)
print(arr4)

[ 1.    3.25  5.5   7.75 10.  ]
[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
[1.         1.18181818 1.36363636 1.54545455 1.72727273 1.90909091
 2.09090909 2.27272727 2.45454545 2.63636364 2.81818182 3.
 3.18181818 3.36363636 3.54545455 3.72727273 3.90909091 4.09090909
 4.27272727 4.45454545 4.63636364 4.81818182 5.        ]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [55]:
#rand()
import numpy as np

var=np.random.rand(2,5)


var1=np.random.rand(1,10)
print(var1)
print(var)

[[0.72874609 0.62905098 0.1618886  0.13686136 0.77071476 0.90057291
  0.90966958 0.00420891 0.49943518 0.23482688]]
[[0.00556402 0.26924401 0.60595314 0.20704414 0.56526598]
 [0.85239921 0.56706395 0.1322766  0.18933718 0.60345954]]


In [56]:
# randn()


var2=np.random.randn(5)
print(var2)

[-0.25886223 -0.21195666 -1.10163174 -2.1067746   1.05778493]


In [57]:
var2=np.random.randn(3,5)
print(var2)

[[ 0.3406681   1.43021567 -1.55060717  0.49466607  1.86403405]
 [-1.2184513   0.1259819   0.03816966 -0.46236532  0.27767452]
 [ 0.05937466  1.60040926 -0.17230015 -0.71992397 -0.27947106]]


In [64]:
var=np.random.ranf(4)
print(var)
var3=np.random.ranf(10)
print(var3)

[0.63296597 0.24100158 0.80877718 0.69549424]
[0.02903585 0.39672038 0.99338502 0.37817441 0.74532752 0.6547722
 0.83628728 0.7153082  0.58376448 0.29437599]


In [69]:
var5=np.random.randint(5,23,5)
print(var5)

print()


var11=np.random.randint(10,50,5)
print(var11)

[21  5  6  8 20]

[15 49 17 10 33]


In [70]:
var=np.array([1.0,1.2,1.3])
print(var)

[1.  1.2 1.3]


In [74]:
var=np.array([1,2,3,4,5])
print("Data type",var.dtype)


var11=np.array([22,34,56,89])
print("var11",var11.dtype)


Data type int64
var11 int64


In [76]:
var=np.array(['a','e','i','o','u'])
print("var",var.dtype)

var <U1


In [79]:
x=np.array([1,2,3,4,5])
print(x)
print("data type",x.dtype)


x=np.array([1,2,3,4,5],dtype=np.int8)
print("Data type:",x.dtype)

[1 2 3 4 5]
data type int64
Data type: int8


In [ ]:
x1=np.array([11,12,13,14,15])
print("data type",x1.dtype)



data type int64


In [82]:
x2=np.array([1,2,3,4])
new=np.float32(x2)
new_one=np.int_(new)



print("Data type:",x2.dtype)
print("data type:",new.dtype)
print("Data type",new_one.dtype)
print(x2)
print(new)
print(new_one)

Data type: int64
data type: float32
Data type int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [87]:
arr=np.array([1,2,3,4,56])

arr1=np.float32(arr)
arr1_one=np.int_(arr1)
print(arr)
print(arr1)

print(arr1_one)





[ 1  2  3  4 56]
[ 1.  2.  3.  4. 56.]
[ 1  2  3  4 56]


In [93]:
x3=np.array([1,2,3,4,5])
new_1=x3.astype(float)
print(new_1)

print(x3)




[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [99]:
import numpy as np
var=np.array([1,2,3,4,5])
var=var+2
print(var)

var1=np.array([1,2,3,4,6])
var2=np.array([1,2,3,4,51])
var2=var1+var2
print(var2)


[3 4 5 6 7]
[ 2  4  6  8 57]


In [103]:
var=np.array([1,2,3,4,5])
arr1=np.add(var,3)
print(arr1)

var1=np.array([1,2,3,4])
var2=np.array([11,12,13,14])
varr=np.add(var1,var2)

print(varr)

[4 5 6 7 8]
[12 14 16 18]


In [107]:
var=np.array([11,12,13,14,15])
var1=var-1
print(var1)


var11=np.array([4,5,6,7,8])
var12=np.array([12,13,14,15,78])
var13=var11-var12
print(var13)

[10 11 12 13 14]
[ -8  -8  -8  -8 -70]


In [110]:
var=np.array([1,2,3,4,5,6])
var1=np.subtract(var,3)
print(var1)


var11=np.array([11,21,31,41,51,61])
var12=np.array([21,22,23,24,25,26])
var13=np.subtract(var11,var12)
print(var13)

[-2 -1  0  1  2  3]
[-10  -1   8  17  26  35]


In [112]:
var=np.array([1,2,3,4])
var=var/3
print(var)


var1=np.array([10,8,13,36])
var2=np.array([1,2,3,4])
var=var1/var2
print(var)

[0.33333333 0.66666667 1.         1.33333333]
[10.          4.          4.33333333  9.        ]


In [114]:
a1=np.array([20,21,22,23,24,25])
a11=np.divide(a1,5)
print(a11)


a12=np.array([11,12,13,14,15])
a13=np.array([22,24,26,28,30])
varr=np.divide(a12,a13)
print(varr)

[4.  4.2 4.4 4.6 4.8 5. ]
[0.5 0.5 0.5 0.5 0.5]


In [118]:
var=np.array([1,2,3,4,5])
var=var%2
print(var)


var1=np.array([2,3,4,5])
var2=np.array([22,23,24,25])
print(var1%var2)

var13=np.mod(var1,var2)
print(var13)

[1 0 1 0 1]
[2 3 4 5]
[2 3 4 5]


In [120]:
var=np.array([1,2,3,4,5])
var=var**2
print(var)

var1=np.array([2,3,4,5,6])
var2=np.array([3,4,5,6,7])
var11=var1**var2
print(var11)

[ 1  4  9 16 25]
[     8     81   1024  15625 279936]


In [121]:
var=np.array([1,2,3,4])
varpow=np.power(var,4)
print(varpow)

[  1  16  81 256]


In [122]:
var=np.array([1,2,3,4,5])
varreci=1/var
print(varreci)

[1.         0.5        0.33333333 0.25       0.2       ]


In [128]:
var21=np.array([[1,2,3,4],[1,2,3,4]])
varadd=var21+4
print(varadd)
print()

var21=np.array([[1,2,3,4],[1,2,3,4]])
var22=np.array([[1,2,3,4],[1,2,3,4]])
var11=var21+var22 
print(var11)


[[5 6 7 8]
 [5 6 7 8]]

[[2 4 6 8]
 [2 4 6 8]]


In [131]:
var21=np.array([[1,2,3,4],[22,23,24,25]])
var=np.add(var21,3)
print(var)

[[ 4  5  6  7]
 [25 26 27 28]]


In [ ]:
var=np.array([1,2,3,89,4,5,9,67,34,56])

print(var)

print("min value:",np.min(var),'position',np.argmin(var))
print('max value:',np.max(var),'position:',np.argmax(var))




print('square root:',np.sqrt(var))



[ 1  2  3 89  4  5  9 67 34 56]
min value: 1 position 0
max value: 89 position: 3
square root: [1.         1.41421356 1.73205081 9.43398113 2.         2.23606798
 3.         8.18535277 5.83095189 7.48331477]


In [ ]:
var=np.array([1,2,3,4,5,6,7])

print('min value',min(var),'position',np.argmin(var))



min value 1 position 0


In [ ]:
import numpy as np

a121=np.array([1,2,3,45,6])
print(a121)






[ 1  2  3 45  6]


In [5]:
var=np.array([1,2,3,45,5])
var1=var*3
print(var1)


var11=np.array([1,2,3,4])
var12=np.array([1,2,3,4])
var111=var11*var12
print(var111)

[  3   6   9 135  15]
[ 1  4  9 16]


In [ ]:
var=np.array([1,2,3,4,5,7])
varmod=var%3

print(varmod)

[ 3  6  9 12 15 21]


In [11]:
var=np.array([1,2,3,4,5,6])
varpow=np.power(var,3)
print(varpow)



a1=np.array([1,2,3,4,5,6])
a2=np.array([2,3,4,56,78,9])

a3=np.power(a1,a2)
print(a3)

[  1   8  27  64 125 216]
[                   1                    8                   81
                    0 -3617894824729806615             10077696]


In [12]:
var=np.array([1,2,3,4])
varreci=1/var
print(varreci)

[1.         0.5        0.33333333 0.25      ]


In [13]:
var=np.array([1,2,3,4,5,6,7,8])

varreci=1/var
print(varreci)

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125     ]


In [16]:
var21=np.array([1,2,3,4,5,6])
varadd=var21+3
print(varadd)

print()


var21=np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])
var22=np.array([[11,1,2,131,13,14],[3,4,5,6,7,89]])

varadd11=var21+var22
print(varadd11)

[4 5 6 7 8 9]

[[ 12   3   5 135  18  20]
 [ 14  16  18  20  22 105]]


In [19]:
var2=np.array([[1,2,3],[5,6,7]])
print(var2)
print(np.sin(var2))

[[1 2 3]
 [5 6 7]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.95892427 -0.2794155   0.6569866 ]]


In [ ]:
# df[['hindhi','math','eng','science','Art']] = df[['hindhi','math','eng','science','Art']].apply(
#     pd.to_numeric, errors='coerce'
# )