In [6]:
import numpy as np
arr_id=np.array([1,2,3,4,5,6])
print(arr_id)

[1 2 3 4 5 6]


In [11]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
print(n1)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
py_list=[1,2,3,4]
print('python list is niumpy',py_list*2)

python list is niumpy [1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
np_array=np.array([1,2,3]) #element wise multiplication 
print('python array multiplication',np_array*2)

python array multiplication [2 4 6]


In [24]:
import time 
start=time.time()
py_list=[i*2 for i in range(1000000)]
print('\n list operation time:',time.time()-start)



 list operation time: 0.10199832916259766


In [25]:
star=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time:",time.time()-start)


 Numpy operation time: 230.61308884620667


In [ ]:
start=time.time()
np_array=np.arange(1000000)*2
print(np_array)

In [30]:
zero=np.zeros([5,5])
print("zeros array",zero)

zeros array [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
one=np.ones([3,4])
print('one array matrix',one)

one array matrix [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
import numpy as np
one=np.ones([3,5])
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
one=np.full([2,2],7)

print("full matrix:",one)

full matrix: [[7 7]
 [7 7]]


In [6]:
# ranom method:
random=np.random.random((3,5))
print('random \n',random)

random 
 [[0.08290134 0.17968441 0.01384171 0.79575395 0.02315745]
 [0.07112352 0.82320557 0.48239678 0.16442236 0.2640031 ]
 [0.78315426 0.74838262 0.48081304 0.21322921 0.83069123]]


In [8]:
sequence=np.arange(0,11,2)
print("sequcence \n",sequence)

sequcence 
 [ 0  2  4  6  8 10]


In [ ]:
### vector ,Matrix  Tensor

In [11]:
vector=np.array([1,2,3,4])
print("vector \n:",vector)

vector 
: [1 2 3 4]


In [12]:
matrix=np.array([[1,2,3],
                 [4,5,6]])
print('matrix:',matrix)

matrix: [[1 2 3]
 [4 5 6]]


In [13]:
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
tensor=np.array([[[1,2,],[24,545]],[[12,34],[45,89]]])
print(tensor)

[[[  1   2]
  [ 24 545]]

 [[ 12  34]
  [ 45  89]]]


In [17]:
# Array propertices
arr=np.array([[1,2,4],[4,5,6]])
print("shape",arr.shape)
print('dimension',arr.ndim)

shape (2, 3)
dimension 2


array dimension 2


In [24]:
array=np.array([[1,2,3,4],[6,7,8,9],[4,6,7.8,9]])
print("array dimension",array.ndim)

array dimension 2


In [22]:
array=np.array([[1,2,3,4],[6,7,8,9],[4,6,78,9]])
print('array sixe',array.size)

array sixe 12


In [29]:
array=np.array([[1,2,3,4],[6,.7,'8',9],[4,6,78,9]])
print("array data type",array.dtype)

array data type <U32


In [ ]:
# Array shape

In [31]:
arr=np.arange(12)

reshaped=arr.reshape((3,4))
print('reshape array',reshaped)

reshape array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
array=np.arange(12)
reshape=array.reshape((3,4))
flattened=reshaped.flatten()
raveled=reshaped.ravel()
print(raveled)
print(flattened)
# print('reshape array print',reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#  

In [47]:
array=np.arange(12)
reshape=array.reshape((3,4))
raveled=reshape.ravel()
transpose=reshape.T

flattened=reshape.flatten()
print(flattened)
print(raveled)
print(transpose)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# transpose

In [49]:
reshape=array.reshape((3,4))
transpose=reshape.T
print(transpose)
print(reshape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# phase two slice

In [ ]:
# Numpy Array operation 

In [53]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print('Basic Slice :',arr[2:7])
print('With step',arr[1:8:2])
print('NEgative indexing',arr[-3])

Basic Slice : [3 4 5 6 7]
With step [2 4 6 8]
NEgative indexing 8


In [58]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr.size)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr)
print('specific element',arr[1,2])
print('Enter row:',arr[1])

9
2
(3, 3)
int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element 6
Enter row: [4 5 6]


In [59]:
print('enter row',arr[:1])

enter row [[1 2 3]]


In [ ]:
# unsorted error

In [ ]:
# unsorted=np.array([3,4,5,61,3,4,6,7,8,9,1])
# print(unsorted)
# print('unsorted Array',np.sort(unsorted))

[ 3  4  5 61  3  4  6  7  8  9  1]
unsorted Array [ 1  3  3  4  4  5  6  7  8  9 61]


In [64]:
array=np.array([1,2,34,1,2,7,6,5,9,7,8])
print(array)
print('unsorted value of array',np.sort(array))

[ 1  2 34  1  2  7  6  5  9  7  8]
unsorted value of array [ 1  1  2  2  5  6  7  7  8  9 34]


In [67]:
array=np.array([[3,1],[1,2],[2,3]])
print('Sorted 2d array by columns',np.sort(array,axis=1))

Sorted 2d array by columns [[1 3]
 [1 2]
 [2 3]]


In [ ]:
# array filter in numpy

In [68]:
numbers=np.array([1,2,3,4,5,6,7,8,9,9,10])
even_number=numbers[numbers%2==0]
print(even_number)

[ 2  4  6  8 10]


In [72]:
array=np.array([1,2,3,4,5,6,7,8,910,12,14,16,18])
number=array[array%2==0]
print(number)
mask=array>4
print(array[mask])

[  2   4   6   8 910  12  14  16  18]
[  5   6   7   8 910  12  14  16  18]


In [ ]:
# facy indexing vs where cloth()

In [75]:
numberes=[1,2,3,4,5,6,7,8,9]
indices=[0,2,4]
print(numberes[indices])


TypeError: list indices must be integers or slices, not list

In [ ]:
# candition Array= 

In [3]:
import numpy as np

number = np.array([1,2,3,4,5,6,7,8,9,10])
condition_array = np.where(number >4, number*6,number)

print(condition_array)

[ 1  2  3  4 30 36 42 48 54 60]


In [4]:
import numpy as np

number = np.array([1,2,3,4,5,6,7,8,9,10])
condition_array = np.where(number >4, number*6,number)

print(condition_array)

[ 1  2  3  4 30 36 42 48 54 60]


In [ ]:
# asdding and removeing data

In [14]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
combine=arr1+arr2
print(combined)
print(combine)

[1 2 3 4 5 6]
[5 7 9]


In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6,8])
c=np.array([7,8,9])
print('Compatiblity shape',a.shape==b.shape)



Compatiblity shape False


In [22]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
print(original)
with_new_row=np.vstack((original,new_row))
print(with_new_row)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [24]:
a=np.array([[23,34],[45,67]])
b=np.array([[45,78]])
print(a)
c=np.vstack((a,b))
print(c)

[[23 34]
 [45 67]]
[[23 34]
 [45 67]
 [45 78]]


In [27]:
original=np.array([[1,2],[3,4]])
new_col=np.array([[7],[8]])
new=np.hstack((original,new_col))
print(new)


[[1 2 7]
 [3 4 8]]


In [32]:
original=np.array([2,3,4,5,6,7,8,9])
original=np.delete(original,3)
print("array after deletion",original)

array after deletion [2 3 4 6 7 8 9]


In [ ]:
# Advance operttion with business exapmple

In [8]:
import numpy as np
import matplotlib.pyplot as plt

sale_data=np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,230000,260000,300000],
    [4,180000,210000,240000,270000],
    [5,160000,185000,205000,230000]
])

print(sale_data)
print('sample data of first three',sale_data[:3])



print("sale_data shape",sale_data.shape)

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
sample data of first three [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
sale_data shape (5, 5)


In [ ]:
# total sale per years find

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

sale_data=np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,230000,260000,300000],
    [4,180000,210000,240000,270000],
    [5,160000,185000,205000,230000]
])
print(np.sum(sale_data,axis=0))
year_total=np.sum(sale_data[: 1:],axis=0)

print(year_total)

[     15  810000  945000 1085000 1240000]
[     1 150000 180000 220000 250000]


In [14]:
import numpy as np
import matplotlib.pyplot as plt

sale_data=np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,230000,260000,300000],
    [4,180000,210000,240000,270000],
    [5,160000,185000,205000,230000]
])
# minimun sales per 
min_sales=np.min(sale_data[:, 1:],axis=1)
print(min_sales)

[150000 120000 200000 180000 160000]


In [ ]:

# max sales per year

300000


In [ ]:
max_sales=np.max(sale_data[:,1:],axis=0)
print(max_sales)

[200000 230000 260000 300000]


In [ ]:
# Average sales per 

In [18]:
avg_sale=np.mean(sale_data[:, 1:],axis=1)
print(avg_sale)


[200000. 152500. 247500. 225000. 195000.]


In [20]:
vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])
print('add of vector',vector1+vector2)
print('multiply of vector',vector1*vector2)

add of vector [ 7  9 11 13 15]
multiply of vector [ 6 14 24 36 50]


In [23]:
restaurant_types=np.array(['biryani','chinese','pizza','burger','cafe'])
print(restaurant_types)
vectorized_upper=np.vectorize(str.upper)
print(vectorized_upper(restaurant_types))

['biryani' 'chinese' 'pizza' 'burger' 'cafe']
['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
# array1=np.array([1,2,3,4,5])
# array2=np.array([6,7,8,9,10])
# array3=np.array([11,12,13,14,15])



In [4]:
import numpy as np

array1=np.array([[1,2,3],[4,5,6]])
array2=np.random.rand(3,3)
array3=np.zeros((4,4))
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

In [5]:
loaded_array1=np.load('array1.npy')
print(loaded_array1)

[[1 2 3]
 [4 5 6]]


In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Dell\Downloads\samsung_global_sales_dataset.csv")
# print(df.head())
df

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,SAMS-00000001,2021-01-01,2021,Q1,January,Argentina,South America,Buenos Aires,Samsung Galaxy Tab S9 Ultra,Galaxy Tab,...,ARS,907.0,1.130820e+06,E-commerce Platform,Samsung Pay,Business,45–54,NaN,3.2,Kept
1,SAMS-00000002,2021-03-23,2021,Q1,March,Argentina,South America,Buenos Aires,Samsung Galaxy S23,Galaxy S,...,ARS,907.0,1.322152e+06,Authorized Reseller,Net Banking,Government,55+,Feature Phone,NaN,Kept
2,SAMS-00000003,2021-05-22,2021,Q2,May,Argentina,South America,Buenos Aires,Samsung Galaxy A34 5G,Galaxy A,...,ARS,907.0,1.964399e+06,Corporate / B2B,Gift Card,Individual,25–34,New User,3.5,Kept
3,SAMS-00000004,2021-07-26,2021,Q3,July,Argentina,South America,Buenos Aires,Samsung T55 27-inch FHD,Monitor,...,ARS,907.0,6.603595e+05,Third-Party Retailer,BNPL (Buy Now Pay Later),Enterprise,55+,NaN,4.0,Kept
4,SAMS-00000005,2021-09-02,2021,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Z Fold 4,Galaxy Z,...,ARS,907.0,2.835246e+06,Authorized Reseller,Gift Card,Business,55+,Android (Other),3.0,Kept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15495,SAMS-00015496,2024-08-08,2024,Q3,August,Vietnam,Asia,Nha Trang,Samsung Galaxy A54 5G,Galaxy A,...,VND,24500.0,1.168332e+07,Samsung Store,BNPL (Buy Now Pay Later),Government,25–34,Android (Samsung),4.0,Kept
15496,SAMS-00015497,2024-08-10,2024,Q3,August,Vietnam,Asia,Nha Trang,Samsung Neo QLED 8K QN900C,Smart TV,...,VND,24500.0,3.520981e+08,Carrier Store,EMI / Installment,Government,55+,NaN,NaN,Returned
15497,SAMS-00015498,2024-09-15,2024,Q3,September,Vietnam,Asia,Nha Trang,Samsung Galaxy Watch 6,Galaxy Watch,...,VND,24500.0,1.373323e+07,Online (Samsung.com),Credit Card,Enterprise,45–54,NaN,NaN,Kept
15498,SAMS-00015499,2024-09-16,2024,Q3,September,Vietnam,Asia,Nha Trang,Samsung 25L Microwave,Appliances,...,VND,24500.0,3.982720e+06,Third-Party Retailer,Debit Card,Business,18–24,NaN,3.3,Kept


In [4]:
df.shape

(15500, 28)