In [9]:
import numpy as np

v=np.array([2,5,4,9,3,8])
np.var(v)
m=np.mean(v)

In [10]:
m

np.float64(5.166666666666667)

In [11]:
y=m-v

In [12]:
b=y**2

In [13]:
b

array([10.02777778,  0.02777778,  1.36111111, 14.69444444,  4.69444444,
        8.02777778])

In [15]:
u=np.sum(b)/len(v)
u

np.float64(6.472222222222222)

In [16]:
v=np.array([2,5,4,9,3,8])
v

array([2, 5, 4, 9, 3, 8])

In [17]:
np.var(v)

np.float64(6.472222222222222)

In [19]:
m=np.mean(v)
m

np.float64(5.166666666666667)

In [20]:
y=m-v

In [21]:
b=y**2

In [22]:
b

array([10.02777778,  0.02777778,  1.36111111, 14.69444444,  4.69444444,
        8.02777778])

In [23]:
u=np.sum(b)/len(v)
u

np.float64(6.472222222222222)

dfg


In [3]:
import numpy as np

v=np.array([2,5,4,9,3,8])
v

array([2, 5, 4, 9, 3, 8])

In [4]:
np.var(v)

np.float64(6.472222222222222)

In [5]:
np.std(v)

np.float64(2.544056253745625)

In [6]:
m=np.mean(v)
m

np.float64(5.166666666666667)

In [1]:
print('heoo')

heoo


In [2]:
# co relation

import numpy as np

v=np.array([2,5,4,9,3,8])
v

array([2, 5, 4, 9, 3, 8])

In [3]:
np.var(v)

np.float64(6.472222222222222)

In [4]:
np.std(v)

np.float64(2.544056253745625)

In [6]:
m=np.mean(v)
m

np.float64(5.166666666666667)

In [8]:
y=m-v
y

array([ 3.16666667,  0.16666667,  1.16666667, -3.83333333,  2.16666667,
       -2.83333333])

In [9]:
b=y**2
b

array([10.02777778,  0.02777778,  1.36111111, 14.69444444,  4.69444444,
        8.02777778])

In [11]:
u=np.sum(b)/len(v)
u

np.float64(6.472222222222222)

In [12]:
c=np.sqrt(u)

In [13]:
c

np.float64(2.544056253745625)

In [ ]:
import pandas as pd


data = {
    "X": [5, 10, 5, 11, 12, 4, 3, 2, 7, 1],
    "Y": [1, 6, 2, 8, 5, 1, 4, 6, 5, 2]
}


df = pd.DataFrame(data)

print(df)

    X  Y
0   5  1
1  10  6
2   5  2
3  11  8
4  12  5
5   4  1
6   3  4
7   2  6
8   7  5
9   1  2


In [15]:
df

,X,Y
0,5,1
1,10,6
2,5,2
3,11,8
4,12,5
5,4,1
6,3,4
7,2,6
8,7,5
9,1,2


In [16]:
df.cov()

,X,Y
X,14.888889,5.333333
Y,5.333333,5.777778


In [17]:
df.corr()

,X,Y
X,1.000000,0.575026
Y,0.575026,1.000000
